CREATE TABLE ALIAS(
    ID INTEGER NOT NULL,
    ALIAS_NAME VARCHAR2(100) NOT NULL,
    RESOURCE_URL VARCHAR2(100) NOT NULL,
    ARTIST_ID INTEGER,
    PRIMARY KEY(ID)
);

CREATE TABLE ARTIST(
    name varchar2(100) NOT NULL,
	ID NUMBER(10) NOT NULL,
    RESOURCE_URL VARCHAR2(100) NOT NULL,
    URI VARCHAR2(100) NOT NULL,
    RELEASES_URL VARCHAR2(100) NOT NULL,
    REAL_NAME VARCHAR2(100) NOT NULL,
    ARTIST_PROFILE VARCHAR2(100) NOT NULL,
    DATA_QUALITY VARCHAR2(100) NOT NULL,
    PRIMARY KEY(ID)
);

CREATE TABLE COMMUNITY(
    ID INTEGER NOT NULL,
    WANT INTEGER,
    HAVE INTEGER,
    PRIMARY KEY(ID)
);

CREATE TABLE RELEASE(
    ID INTEGER NOT NULL,
    COUNTRY VARCHAR2(50) NOT NULL,
	RELEASE_YEAR INTEGER,
    RELEASE_TYPE VARCHAR2(50),
    MASTER_ID INTEGER,
    MASTER_URL VARCHAR2(100),
    URI VARCHAR2(100),
    CATNO VARCHAR2(50),
    TITLE VARCHAR2(100),
    THUMB VARCHAR2(500),
    COVER_IMAGE VARCHAR2(500),
    RESOURCE_URL VARCHAR2(100),
    COMMUNITY_ID INTEGER,
    PRIMARY KEY(ID),
    FOREIGN KEY (COMMUNITY_ID) REFERENCES COMMUNITY(ID)
);

CREATE TABLE IMAGE(
    ID INTEGER NOT NULL,
	IMAGE_TYPE VARCHAR2(10) NOT NULL,
	URI VARCHAR2(100) NOT NULL,
	RESOURCE_URL VARCHAR2(100) NOT NULL,
	URI_150 VARCHAR2(150) NOT NULL,
    WIDTH INTEGER NOT NULL,
	HEIGHT INTEGER NOT NULL,
    ARTIST_ID INTEGER,
    PRIMARY KEY(ID)
);

CREATE TABLE STYLE(
    ID INTEGER NOT NULL,
	STYLE_NAME VARCHAR2(100) NOT NULL,
    RELEASE_ID INTEGER,
    PRIMARY KEY(ID),
    FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE(ID)
);

CREATE TABLE BARCODE(
    ID INTEGER NOT NULL,
    BARCODE_VALUE VARCHAR2(50) NOT NULL,
    RELEASE_ID INTEGER,
    PRIMARY KEY(ID),
    FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE(ID)
);

CREATE TABLE GENRE(
    ID INTEGER NOT NULL,
	GENRE_NAME VARCHAR2(100) NOT NULL,
    RELEASE_ID INTEGER,
    PRIMARY KEY(ID),
    FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE(ID)
);

CREATE TABLE FORMAT(
    ID INTEGER NOT NULL,
	FORMAT_NAME VARCHAR2(100) NOT NULL,
    RELEASE_ID INTEGER,
    PRIMARY KEY(ID),
    FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE(ID)
);
CREATE TABLE LABEL(
    ID INTEGER NOT NULL,
	LABEL_NAME VARCHAR2(100) NOT NULL,
    RELEASE_ID INTEGER,
    PRIMARY KEY(ID),
    FOREIGN KEY (RELEASE_ID) REFERENCES RELEASE(ID)
);